name: SeeDevice
version: "0.0.6"
author: Palente
main: SeeDevice\SeeDevice
description: "More easy to get Device of Player"
website: "https://github.com/Palente"
api: 
  - "3.0.0"
  - "3.0.2"
  - "4.0.0"

commands: 
  seedevice: 
    description: "See The device of a player"
    permission: SeeDevice.command.sd
    usage: "/seedevice [player]"
  fakeos:
    description: "Change the device"
    permission: SeeDevice.command.fakeos
    usage: "/fakeos <playername-self> <name_of_device>"

permissions:
 SeeDevice.*:
  default: op
  description: Allows to control all of Available thing
  children:
   SeeDevice.command.*:
    default: op
    description: Allows to use all of commands 
    children:
     SeeDevice.command.sd:
      default: op
      description: Allows to see a the device of a player
     SeeDevice.command.fakeos:
      default: op
      description: Allows to edit the device of a Player

#with yamllint.com